Repository ipt-cryptolabs/aaf-labs-2023, pull requests merged in 2024-01, with the labels that each got.

#2 [V-1] Balatska (FI-13), Krivoshapova (FI-13)
  balatska_fi-13_krivoshapova_fi-13_cp1/.gitignore
  balatska_fi-13_krivoshapova_fi-13_cp1/CMakeLists.txt
  balatska_fi-13_krivoshapova_fi-13_cp1/lab_py/main.py
  balatska_fi-13_krivoshapova_fi-13_cp1/src/functions.cpp
  balatska_fi-13_krivoshapova_fi-13_cp1/src/functions.h
  balatska_fi-13_krivoshapova_fi-13_cp1/src/main.cpp
  balatska_fi-13_krivoshapova_fi-13_cp1/src/parser.cpp
  balatska_fi-13_krivoshapova_fi-13_cp1/src/parser.h
Labels: needs_cleanup

#6 [V-2] Nedashkivska (FI14), Medvediev (FI-14)
  Nedashkivska_Medvediev_FI-14/.gitignore
  Nedashkivska_Medvediev_FI-14/database.py
  Nedashkivska_Medvediev_FI-14/main.py
  Nedashkivska_Medvediev_FI-14/myparser.py
Labels: incomplete_impl

#34 [V-7] Kyrychenko (FI-14)
  kyrychenko_fi-14/laba_1.py
Labels: parser_issues, impl_issues

#36 [V-4] Patsora(FI-13), Tatarynova(FI-13) (v.2)
  patsora_tatarynova_fi-13/CMakeLists.txt
  patsora_tatarynova_fi-13/DB1/test_join1.csv
  patsora_tatarynova_fi-13/DB1/test_join2.csv
  patsora_tatarynova_fi-13/DB_OAA.cpp
  patsora_tatarynova_fi-13/Database.hpp
  patsora_tatarynova_fi-13/Table.hpp
Labels: impl_issues

#37 [V-9] Prunchak (FI-14), Pavlenko (FI-14)
  prunchak_fi-14_pavlenko_fi-14/.gitignore
  prunchak_fi-14_pavlenko_fi-14/database.py
  prunchak_fi-14_pavlenko_fi-14/main.py
  prunchak_fi-14_pavlenko_fi-14/parser.py
Labels: inefficient
